# Generated by Django 5.2.4 on 2025-11-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(verbose_name='From')),
                ('date_to', models.DateTimeField(verbose_name='To')),
                ('apartman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termini', to='apartman.apartman')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termini',
                'ordering': ['date_from'],
            },
        ),
    ]
