# Generated by Django 5.2.4 on 2025-11-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='value',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
    ]
