# Generated by Django 5.2.4 on 2025-11-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_termin_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='date_from',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='date_to',
            field=models.DateField(verbose_name='To'),
        ),
    ]
