# Generated by Django 5.2.4 on 2025-11-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_alter_termin_date_from_alter_termin_date_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termin',
            options={'ordering': ['date_from'], 'verbose_name': 'Cijena', 'verbose_name_plural': 'Cijene'},
        ),
    ]
