# Generated by Django 5.2.4 on 2025-08-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_disabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
