# Generated by Django 5.2.4 on 2025-09-09 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ImageConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('is_labeled_ai', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='gallery.image')),
                ('image_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='gallery.image')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSideProfileValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('profile_id', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_profile_values', to='gallery.image')),
            ],
        ),
    ]
