# Generated by Django 5.2.4 on 2025-11-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_per_night', models.BooleanField(default=False)),
                ('is_per_person', models.BooleanField(default=False)),
                ('is_global_default', models.BooleanField(default=False, help_text='Automatski dodaj na svaki novi booking?')),
            ],
        ),
    ]
