# Generated by Django 5.2.4 on 2025-11-22 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_bookingservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Od datuma')),
                ('date_to', models.DateField(verbose_name='Do datuma')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sezonska Cijena')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='services.service', verbose_name='Usluga')),
            ],
            options={
                'verbose_name': 'Sezonska Cijena Usluge',
                'verbose_name_plural': 'Cjenik Usluga (Sezonski)',
                'ordering': ['service', 'date_from'],
            },
        ),
    ]
