# Generated by Django 5.2.4 on 2025-11-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprice',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='is_per_night',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='price',
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Usluga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Količina'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_global_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='services.service'),
        ),
    ]
