# Generated by Django 5.2.4 on 2025-11-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_serviceprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cijena (Fiksirana)'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Ukupno (Stavka)'),
        ),
    ]
