# Generated by Django 5.2.4 on 2025-11-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ukupna cijena bookinga'),
        ),
    ]
