# Generated by Django 5.2.4 on 2025-11-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0002_booking_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSearch',
            fields=[
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Search',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookingengine.booking',),
        ),
    ]
