# Generated by Django 5.2.4 on 2025-11-22 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0005_alter_booking_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatni zahtjevi (Napomene)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Popust Iznos (EUR)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Popust %'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Datum uplate')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Opis')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookingengine.booking')),
            ],
            options={
                'verbose_name': 'Uplata',
                'verbose_name_plural': 'Uplate',
            },
        ),
    ]
