# Generated by Django 5.2.4 on 2025-11-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0006_booking_additional_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Popust Iznos (EUR)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Popust %'),
        ),
    ]
