# Generated by Django 5.2.4 on 2025-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingengine', '0007_alter_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_percent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Popust Iznos (EUR)'),
        ),
    ]
