# Generated by Django 5.2.4 on 2025-11-13 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in square meters (m²)', max_digits=10)),
                ('opis', models.TextField(blank=True, null=True)),
                ('additional_content', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartmani', to='company.company')),
            ],
        ),
    ]
