# Generated by Django 5.2.4 on 2025-11-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartman',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of guests'),
        ),
    ]
