# Generated by Django 5.2.4 on 2025-11-14 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartman', '0002_apartman_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apartman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='apartman.apartman')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('apartman', 'date')},
            },
        ),
    ]
