# Generated by Django 5.2.4 on 2025-11-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartman', '0003_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
