# Generated by Django 5.2.4 on 2025-11-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartman', '0004_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartman',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default price in cents.', max_digits=10),
        ),
    ]
