# Generated by Django 5.2.4 on 2025-11-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartman', '0005_apartman_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartman',
            name='capacity_additional',
            field=models.PositiveIntegerField(default=1, help_text='Additional number of guests'),
        ),
        migrations.AddField(
            model_name='apartman',
            name='capacity_additional_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default price šer person', max_digits=10),
        ),
        migrations.AddField(
            model_name='apartman',
            name='capacity_basic',
            field=models.PositiveIntegerField(default=1, help_text='Number of guests'),
        ),
        migrations.AlterField(
            model_name='apartman',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Max number of guests'),
        ),
    ]
