# Generated by Django 5.2.4 on 2025-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="Jedinstvena putanja do postavke, npr. 'general.site_name'", max_length=255, unique=True, verbose_name='Putanja (ključ)')),
                ('value', models.CharField(blank=True, help_text='Vrijednost postavke.', max_length=2000, verbose_name='Vrijednost')),
                ('default', models.BooleanField(default=False, help_text='Označava je li ovo sistemska, zadana postavka.', verbose_name='Zadana postavka')),
            ],
            options={
                'verbose_name': 'Postavka',
                'verbose_name_plural': 'Postavke',
            },
        ),
    ]
