# Generated by Django 5.2.4 on 2025-09-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgeneration',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens generated in the response.', verbose_name='Completion Tokens'),
        ),
        migrations.AddField(
            model_name='contentgeneration',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens used for the prompt.', verbose_name='Prompt Tokens'),
        ),
    ]
