# Generated by Django 5.2.4 on 2025-09-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0002_contentgeneration_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgeneration',
            name='image_count',
            field=models.PositiveIntegerField(default=0, help_text='Ukupan broj slika generiran za ovaj unos.', verbose_name='Broj generiranih slika'),
        ),
    ]
