# Generated by Django 5.2.4 on 2025-09-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0002_contentgeneration_completion_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentgeneration',
            name='completion_tokens',
        ),
        migrations.RemoveField(
            model_name='contentgeneration',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='contentgeneration',
            name='prompt_tokens',
        ),
    ]
