# Generated by Django 5.2.4 on 2025-09-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0003_remove_contentgeneration_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgeneration',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens generated in the response.', verbose_name='Completion Tokens'),
        ),
        migrations.AddField(
            model_name='contentgeneration',
            name='image_count',
            field=models.PositiveIntegerField(default=0, help_text='Ukupan broj slika generiran za ovaj unos.', verbose_name='Broj generiranih slika'),
        ),
        migrations.AddField(
            model_name='contentgeneration',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens used for the prompt.', verbose_name='Prompt Tokens'),
        ),
        migrations.AddField(
            model_name='contentgeneration',
            name='rules_geminy',
            field=models.TextField(blank=True, help_text='Dodatna pravila ili kontekst koji se dodaje na Gemini request.', verbose_name='Gemini Pravila'),
        ),
        migrations.AddField(
            model_name='contentgeneration',
            name='rules_imagen',
            field=models.TextField(blank=True, help_text='Dodatna pravila ili stil koji se dodaje na finalni prompt za Imagen.', verbose_name='Imagen Pravila'),
        ),
    ]
