# Generated by Django 5.2.4 on 2025-09-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0003_contentgeneration_image_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgeneration',
            name='rules_geminy',
            field=models.TextField(blank=True, help_text='Dodatna pravila ili kontekst koji se dodaje na Gemini request.', verbose_name='Gemini Pravila'),
        ),
        migrations.AddField(
            model_name='contentgeneration',
            name='rules_imagen',
            field=models.TextField(blank=True, help_text='Dodatna pravila ili stil koji se dodaje na finalni prompt za Imagen.', verbose_name='Imagen Pravila'),
        ),
    ]
