# Generated by Django 5.2.4 on 2025-09-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('post_url', models.URLField(max_length=256, unique=True)),
                ('post_image', models.URLField(max_length=512)),
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField()),
                ('post_song', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Instagram Post',
                'verbose_name_plural': 'Instagram Posts',
                'ordering': ['-publish_date'],
            },
        ),
    ]
