# Generated by Django 5.2.4 on 2025-09-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Instagram objava', 'verbose_name_plural': 'Instagram objave'},
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Broj komentara'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Broj lajkova'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='instagram_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Instagram ID'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_image',
            field=models.URLField(blank=True, max_length=1024, verbose_name='URL slike'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_song',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pjesma'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL objave'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum objave'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Objavljeno'),
        ),
    ]
