# Generated by Django 5.2.4 on 2025-09-07 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_instagrampost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visits', models.PositiveIntegerField(default=0, verbose_name='Posjete profilu')),
                ('followers_delta_from_last_week', models.IntegerField(default=0, verbose_name='Promjena pratitelja (tjedan)')),
                ('gender_graph', models.JSONField(default=dict, verbose_name='Graf po spolu')),
                ('all_followers_age_graph', models.JSONField(default=dict, verbose_name='Graf po dobi (svi)')),
                ('followers_top_cities_graph', models.JSONField(default=dict, verbose_name='Top gradovi pratitelja')),
                ('followers_top_countries_graph', models.JSONField(default=dict, verbose_name='Top države pratitelja')),
                ('week_daily_followers_graph', models.JSONField(default=dict, verbose_name='Dnevni broj pratitelja (tjedan)')),
                ('impressions', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Impresije')),
                ('reach', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Doseg')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Dohvaćeno')),
            ],
            options={
                'verbose_name': 'Statistika računa',
                'verbose_name_plural': 'Statistike računa',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='like_count',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='instagram_pk',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Instagram PK'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='instagram_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Instagram ID (Code)'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_image',
            field=models.FileField(blank=True, max_length=512, upload_to='IG/', verbose_name='Slika'),
        ),
        migrations.CreateModel(
            name='ContentInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0, verbose_name='Lajkovi')),
                ('comments', models.IntegerField(default=0, verbose_name='Komentari')),
                ('reach', models.IntegerField(default=0, verbose_name='Doseg')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impresije')),
                ('saved', models.IntegerField(default=0, verbose_name='Spremanja')),
                ('shares', models.IntegerField(blank=True, default=0, null=True, verbose_name='Dijeljenja')),
                ('profile_visits', models.IntegerField(default=0, verbose_name='Posjete profilu')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Dohvaćeno')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='instagram.instagrampost', verbose_name='Objava')),
            ],
            options={
                'verbose_name': 'Statistika objave',
                'verbose_name_plural': 'Statistike objava',
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
    ]
